# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b33a919ba7eb48712932a46a0c5deb7e7d459f4d50210fa220ab4c16b661b800278711d2d5425adbac43679673c0edaaffaf755446b1982cc37e580daf9e8813

test:
  secret_key_base: d31a2355f768d6ccc356d54de5039e3fb49151ac619ef4de9b26a10b27ec81f2b639346be68d4676f7f09b12f37007467e208f60fe0e623d77b0521a4a8a5b0b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
